# Book settings
title: Schiphol Flight Emission
author: Casper Sikkema, Joshua Appiah, Mohammed Khalifa
copyright: "2024"
logo: static/images/logo.jpg

# HTML settings
html:
  extra_css: 
    - css/custom.css
  favicon: static/images/icon.ico
  use_repository_button: true
  use_issues_button: true
  extra_navbar: _templates/custom_header.html

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/RISE020/InfoVis
  path_to_book: docs
  branch: main

# Add launch buttons
launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
